name: Playwright Tests
on:
  push:
    branches: [ main, cleanup ]
  pull_request:
    branches: [ main, cleanup ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-v1
        restore-keys: |
          playwright-${{ runner.os }}-
          playwright-
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      env:
        TESTS_BASE_URL: ${{ secrets.TESTS_BASE_URL }} 
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
